### PR TITLE
Change Order for compiler

### PR DESCRIPTION
**Pull request by s00500**
Change the order to avoid an error

### CODE REVIEW

**Comment by Gianbacchio** [comment]
Hi, Do you get errors compiling the sketch?
strange, I don't...

**Comment by s00500** [comment]
Hi, yes I got some... don't know exactly why but it seems to be a thing with my particular ide install... anyway...

**Comment by manbade** [comment]
From IDE 1.6.7 it´s necessary declare funtion before call it.
Move the function Bot_ExecMessages i.e. before loop()

**Comment by Gianbacchio** [comment]
thank you for the info.
I will update soon the library also including Telegram App 2.0
modifications

2016-05-02 20:32 GMT+02:00 Manbade VIA Manbait Untamed REEF <
notifications@github.com>:

> From IDE 1.6.7 it´s necessary declare funtion before call it.
> Move the function Bot_ExecMessages i.e. before loop()
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/Gianbacchio/ESP8266-TelegramBot/pull/2#issuecomment-216320777>
>



-- 
*Giancarlo Bacchio*
mob. +39 3313136813
skype: giancarlo_bacchio

**Comment by Gianbacchio** [comment]
updated example sketches according requests

**Pull request closed without merging**
